sudo: false
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/protobuf

language: java

env: MAVEN_OPTS="-XX:MaxPermSize=128m"

before_install:
  - bash support/scripts/install-protobuf.sh
  - export PATH=$PATH:$HOME/protobuf/bin
jdk:
  - oraclejdk7
script:
  - protoc --version
  -  mvn test

