spring:
  jackson:
    property-naming-strategy:   SNAKE_CASE
    default-property-inclusion: NON_NULL

logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
        web: ERROR
