spring:
  jackson:
    property-naming-strategy:   SNAKE_CASE
    serialization:
      WRITE_NULL_MAP_VALUES: false

logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
        web: ERROR
