spring:
  jackson:
    timeZone: Asia/Shanghai
    property-naming-strategy:   SNAKE_CASE
    default-property-inclusion: NON_NULL
    parser:
      ALLOW_SINGLE_QUOTES: true

      ALLOW_UNQUOTED_FIELD_NAMES: true

server.error.includeStacktrace: ON_TRACE_PARAM

logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
        web: WARN
      hibernate:
        SQL: debug

