spring:
  jackson:
    property-naming-strategy:   CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    serialization:
      WRITE_NULL_MAP_VALUES: false

logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
        web: ERROR
